const CONFIG = {
    introTitle: 'Em ơi!',
    introDesc: 'Em như 7 hằng đẳng thức vậy. Vì nó đáng nhớ. Cho phép anh tìm hiểu về em nhé!!',
    btnIntro: 'hihi',
    title: 'Anh có thể chờ em từ sáng đến tối. Chỉ để thấy em trong bộ đồ anh yêu. Có em ngồi phía sau, đi đâu cũng được 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'em đồng ý <33',
    btnNo: 'Không, Anh trai à :3',
    question:'hãy để anh được làm những điều em thích nhé ❤',
    btnReply: 'Gửi cho anh ❤',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Xem được thì phản hồi lại cho anh nhé.',
    btnAccept: 'Okiiiii lun ❤',
    messLink: 'https://www.facebook.com/profile.php?id=100030096814354', 
}